// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC8pI5FEdNALBa0rkDrb7aD8XdAp6Gg04',
    appId: '1:269823945315:web:54c45a2bb08d506465e656',
    messagingSenderId: '269823945315',
    projectId: 'learns-c86ea',
    authDomain: 'learns-c86ea.firebaseapp.com',
    storageBucket: 'learns-c86ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz5dgq5or_8F2cDekAVXrF4MEqihsb7lc',
    appId: '1:269823945315:android:ed8669747381a3aa65e656',
    messagingSenderId: '269823945315',
    projectId: 'learns-c86ea',
    storageBucket: 'learns-c86ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8xtxOmQ_DtKYLGAzLBRq0D8ecrSK4ijk',
    appId: '1:269823945315:ios:8ae2946e65e3bd7365e656',
    messagingSenderId: '269823945315',
    projectId: 'learns-c86ea',
    storageBucket: 'learns-c86ea.appspot.com',
    iosClientId: '269823945315-gh7obm5hevf7a76831p0fsi2u8uce493.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.espoch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8xtxOmQ_DtKYLGAzLBRq0D8ecrSK4ijk',
    appId: '1:269823945315:ios:3fdbb05685ee0fee65e656',
    messagingSenderId: '269823945315',
    projectId: 'learns-c86ea',
    storageBucket: 'learns-c86ea.appspot.com',
    iosClientId: '269823945315-ub0rmuf12aii318t00vik5f52fo1a2vq.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.espoch.RunnerTests',
  );
}
